export const styles = {
  container: "flex flex-col",
  header: "text-xl text-textColor font-yekanbakh font-bold",
  subHeaders: "flex items-center gap-4 mt-2",
  subHeader: "flex items-center",
  subHeaderTitle: "text-[#666] font-bold",
  subHeaderValue: "text-primaryColor",
  infoBox: "mt-15px flex flex-col gap-2",
  infoTitle: "text-[18px] text-textColor font-bold",
  colorBox: "inline-block w-[30px] h-[30px] rounded-6px",
  acceptDevicesCon: "flex flex-col",
  acceptDeviceTitle: "flex items-center text-textColor",
  infoIcon: "fill-iconColor me-2 w-[15px] h-[15px]",
  acceptDevices: "flex items-center gap-4 text-[#666] mt-2",
  partCon: "flex items-center",
  acceptDeviceItem: "p-2 border-l-2 border-[#e8e8e8] font-yekanbakh",
  colorPricesContainer: "flex flex-wrap gap-4 items-center",
  colorPriceItem: "flex items-center gap-[10px] text-subtitleColor",
  colorPricesItem: "flex flex-col",
  colorPriceBox: "inline-block w-[20px] h-[20px] rounded-full",
  colorsRow: "flex items-center gap-2",
  colorsItem: "inline-block w-[30px] h-[30px] rounded-6px transition",
  colorsItemActive: "scale-110",
  discount: "text-subTitleColor line-through",
};
