export const styles = {
  header: "bg-cardColor px-2 no-print",
  headerRow: "flex items-center justify-between max-w-7xl mx-auto",
  startRow: " flex items-center gap-4",
  navbar: "hidden laptop:block",
  navbarList: "list-none flex items-center gap-4",
  navbarItem: "text-textColor transition-colors hover:text-primaryColor",
  endRow: "flex items-center gap-4",
  headerButtonContainer: "hidden laptop:flex items-center gap-4",
  headerMobileButtonContainer: "flex items-center gap-4",
  headerButton: "fill-iconColor transition hover:fill-primaryColor",
  mobileStyle: "flex laptop:hidden items-center justify-between mt-2 pb-2",
  menuButton: "fill-iconColor",
  mobileNavbarList: "list-none flex flex-col gap-4",
};
